name: Generate GitHub metrics

on:
  schedule:                   # 毎日 01:00(JST) に自動実行
    - cron:  '0 16 * * *'
  workflow_dispatch:          # 手動実行も可

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}   # ← ここが決定版
          user:  ${{ github.repository_owner }}
          template: classic
          plugin_languages: yes
          base: header, activity, community, repositories
          config_timezone: Asia/Tokyo
          plugin_lines: yes                    # グラフを有効化
          plugin_languages_sections: most-used, recently-used
